# Generated by Django 3.1.2 on 2021-06-26 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantdiseaseapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plantdiseaseimage',
            old_name='plantimage',
            new_name='plantimage1',
        ),
        migrations.AddField(
            model_name='plantdiseaseimage',
            name='plantimage2',
            field=models.ImageField(default='null', upload_to='images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plantdiseaseimage',
            name='plantimage3',
            field=models.ImageField(default='null', upload_to='images/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='plantdiseaseimage',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
